[package]
name = "nightjar"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "libnightjar"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hudhook = "0.6.5"
imgui = "0.11.0"
imgui-sys = "0.11.0"
